# Generated by Django 2.2.10 on 2020-06-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0002_fly_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='size',
            field=models.CharField(default='12', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fly',
            name='time_of_year',
            field=models.DateField(auto_now_add=True),
        ),
    ]
