# Generated by Django 2.2.8 on 2020-01-17 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20200114_0552'),
        ('system', '0003_auto_20191229_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_images', to='social.Post'),
        ),
    ]
