# Generated by Django 2.2.10 on 2020-06-10 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '__first__'),
        ('river', '__first__'),
        ('system', '0006_imagefilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='fish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fish_images', to='fish.Fish'),
        ),
        migrations.AddField(
            model_name='image',
            name='hole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='river.Hole'),
        ),
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='social.Post'),
        ),
    ]
