# Generated by Django 2.2.10 on 2020-06-10 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('river', '__first__'),
        ('fly', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Rainbow Trout', 'Rainbow Trout'), ('Brown Trout', 'Brown Trout'), ('Brooke Trout', 'Brooke Trout'), ('Tiger Trout', 'Tiger Trout'), ('Lake Trout', 'Lake Trout'), ('White Fish', 'White Fish'), ('Grayling', 'Grayling')], default='Rainbow Trout', max_length=50)),
                ('length', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('fly', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fly.Fly')),
                ('hole', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='river.Hole')),
            ],
        ),
    ]
