# Generated by Django 2.2.8 on 2019-12-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='sponsor',
            field=models.UUIDField(default='f0a066f6-2281-468e-bdba-2ca79db5e9b4'),
        ),
    ]
