# Generated by Django 2.2.8 on 2020-01-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0001_initial'),
        ('user', '0003_auto_20191231_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='invites',
            field=models.ManyToManyField(related_name='invites', to='invites.Invite'),
        ),
    ]
