# Generated by Django 2.2.10 on 2020-06-10 19:54

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='River',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=150)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='user_photos')),
                ('time_of_year', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=1000)),
                ('time_of_year', models.DateField(auto_now_add=True)),
                ('water_level', models.CharField(max_length=5)),
                ('water_temperature', models.CharField(max_length=3)),
                ('flies', models.ManyToManyField(related_name='flies_used', to='fly.Fly')),
                ('river', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='river.River')),
            ],
        ),
    ]
